nvidia: add module to initrd
NixOS/nixos-hardware pull request #1144
Opened 2024-09-27 11:22 UTC by Mic92

So it seems sometimes needed and sometimes not.
So my question is, do we always want nvidia in initrd? At least for intel, this is the way to go.

###### Description of changes

###### Things done

- [ ] Tested the changes in your own NixOS Configuration
- [ ] Tested the changes end-to-end by using your fork of `nixos-hardware` and
      importing it via `<nixos-hardware>` or Flake input

2024-09-27 11:23 UTC, Mic92 commented
cc @ahoneybun

2024-09-27 11:26 UTC, Mic92 commented
cc @matdibu

2024-09-27 11:27 UTC, Mic92 commented
cc @jopejoe1

2024-09-27 11:32 UTC, Mic92 commented
cc @felipelalli

2024-09-27 15:38 UTC, matdibu commented
what's the size difference with this included?

2024-09-28 16:01 UTC, Mic92 commented
> what's the size difference with this included?

~/git/nixpkgs main
% du -sh /nix/store/xsdqp0p1maw6pwj32zmdp4qanbxk5lqg-nvidia-open-6.6.52-560.35.03/lib/modules/6.6.52/kernel/drivers/video/nvidia.ko.xz
6.4M

2024-09-28 16:01 UTC, Mic92 commented
It's noticeable.

2024-09-28 16:03 UTC, Mic92 commented
Ok. Here some explanation from a nvidia forum: https://forums.developer.nvidia.com/t/when-it-makes-sense-to-load-nvidia-modules-into-initramfs-drm-kernel-mode-setting/198266

> Nowadays, the driver should be added to the initrd for a simple reason: timing. Modern pcie ssd systems boot so fast that without loading it from initrd chances are high that the driver isn’t initialized when the Xserver/Wayland compositor has already started so you end up with a broken graphics system.
> Sidenotes: things like ‘early kms’ and stuff don’t apply to the nvidia driver since it provides neither fbdev nor kms console. The console will always be running on vga fb or efifb depending on boot method (bios/efi).
nvidia-drm.modeset=1 thus doesn’t have any influence on the console but this is needed for wayland and enabling prime sync on hybrid graphics systems.

2024-09-28 16:07 UTC, Mic92 commented
^ However I think we could also solve this more elegant with the right systemd service instead.

2024-09-28 18:49 UTC, matdibu commented
> the nvidia driver ... provides neither fbdev nor kms console
but
> Additionally, with the driver version 545 and above, you can also set the experimental nvidia_drm.fbdev=1 parameter, which is required to tell the NVIDIA driver to provide its own framebuffer device instead of relying on efifb or vesafb, which do not work under simpledrm
https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

2024-09-30 22:16 UTC, ahoneybun commented
@matdibu do we want testing to confirm which works better? I can provide that if you do not have a NVIDIA laptop, just let me know what you want me to test.

2024-10-01 13:03 UTC, matdibu commented
I have a [tigerlake+turing laptop](https://github.com/NixOS/nixos-hardware/tree/master/dell/precision/5560), but I don't really know what the pitfalls of this are.

The way I see it, this is an increase in the initrd size (bad) that helps with nvidia compatibility (good).

Seeing as an "ESP is full" problem is much simpler to deal with than "nvidia gpu broke again", I'd say this is a good tradeoff.

As a sidenote, it seems my laptop's `initrd`'s are about 34M, with `[ "xe" "i915" "nvme" "zfs" "dm_mod" ]` in `config.boot.initrd.kernelModules`, so a 6.4M module is about +18% increase in size.

2024-10-01 13:03 UTC, matdibu approved these changes

2024-10-01 13:25 UTC, matdibu commented
on a second thought, it seems like the difference is not just the 6.4MB of `nvidia.ko.xz`
with `config.boot.initrd.kernelModules = [ "xe" "nvidia" "nvme" "zfs" "dm_mod" ]`, it jumped up to 82MB:

```
[root@precision5560:/boot/EFI/nixos]# ls -lh initrd-*
-rw-r----- 1 root root 34M Sep 29 15:12 initrd-6.10.11-23imcahzihf5glgzjwhxl3irffyj7qzzfvurexste5gqys6msviq.efi
-rw-r----- 1 root root 34M Sep 29 00:04 initrd-6.10.11-r5fu2inke2v5nd2ztb5uhrxefhefkzkq6aidaukct624ksjc53kq.efi
-rw-r----- 1 root root 34M Sep 30 15:20 initrd-6.10.11-umlundootqugfa66smudamim25zszme7fh5z6jld3r4ifmzmprwq.efi
-rw-r----- 1 root root 34M Oct  1 11:32 initrd-6.10.12-ibtipyr6t2xgch4f6a2ru6sn5wbsffyrdx4yk6e5mfuhfp7k2qsa.efi
-rw-r----- 1 root root 86M Oct  1 16:09 initrd-6.10.12-tlc4aog6x4kzdpeezd6jlfpoofbbnjtch6bipfnixrkpnlvnovhq.efi
-rw-r----- 1 root root 82M Oct  1 16:15 initrd-6.10.12-ufetcjq3xnljio6iaondc4ct63flrxjlgx2glczgetz6ttlydata.efi
```

2024-10-01 13:30 UTC, matdibu commented
we might need the help of someone who understands the current situation with nvidia, their fbdev, and all other related components.

there's a lot of old info on the web, and a lot of hearsay

maybe in the end, including nvidia in initrd doesn't bring any compatibility benefits

2024-10-01 13:34 UTC, matdibu requested changes
need more info on whether this is needed on modern setups, and what setups is this explicitly needed for

2024-10-04 15:21 UTC, Mic92 commented
> we might need the help of someone who understands the current situation with nvidia, their fbdev, and all other related components.
> 
> there's a lot of old info on the web, and a lot of hearsay
> 
> maybe in the end, including nvidia in initrd doesn't bring any compatibility benefits in modern setups (with recent hardware, drivers and kernel)

I also haven't had a confirmed case yet, where this was actually a problem.

2024-10-04 15:21 UTC, closed without merging